src/Jaxxes/SeleccionProcesBundle/Entity/SelectionProcessCandidate.php
<?php

namespace Jaxxes\SeleccionProcesBundle\Entity;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

use Doctrine\ORM\Mapping as ORM;

/**
 * SelectionProcessCandidate
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class SelectionProcessCandidate implements  UserInterface
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
    * @ORM\ManyToOne(targetEntity="Jaxxes\SeleccionProcesBundle\Entity\SelectionProcess")
    */
    protected $selectionProcess;
    
    /**
    * @ORM\ManyToOne(targetEntity="Jaxxes\CandidateBundle\Entity\Candidate")
    */
    protected $candidate;

    /**
    * @ORM\OneToMany(targetEntity="Jaxxes\VirtualInterviewBundle\Entity\VirtualInterviewSelectionProcessCandidate", mappedBy="SelectionProcessCandidate", cascade={"persist", "remove"} )
    */
    protected $answers;

    /**
    * @ORM\OneToMany(targetEntity="Jaxxes\SeleccionProcesBundle\Entity\ResumePrivateCandidate", mappedBy="SPCResumePrivate", cascade={"persist", "remove"} )
    */
    protected $answersResumePrivate;
    
        
    /**
     * @var string salt
     *
     * @ORM\Column(name="salt", type="string", length=255, nullable=true )
     */
    protected $salt;
    
       
    /**
     * @var boolean
     *
     * @ORM\Column(name="active", type="boolean", nullable=true)
     */
    private $active;

    /**
     * @var string
     *
     * @ORM\Column(name="usercandidate", type="string", length=255)
     */
    private $usercandidate;
 
    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=255)
     */
    private $password;
    
    /**
     * @var datetime
     *
     * @ORM\Column(name="dateStart", type="date", nullable=true)
     * @Assert\DateTime()
     */
    private $dateStart;
    
    /**
     * @var string
     *
     * @ORM\Column(name="hourStart", type="string", length=255, nullable=true)
     */
    private $hourStart;
    
    /**
     * @var boolean
     *
     * @ORM\Column(name="finishtest", type="boolean", nullable=true)
     */
    private $finishtest;
    
    public function __construct() {
        $this->answers = new ArrayCollection();
        $this->answersResumePrivate = new ArrayCollection();
    }
    
    public function __toString()
    {
        return $this->getCandidate()->__toString();
    }


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set active
     *
     * @param boolean $active
     * @return SelectionProcessCandidate
     */
    public function setActive($active)
    {
        $this->active = $active;

        return $this;
    }

    /**
     * Get active
     *
     * @return boolean 
     */
    public function getActive()
    {
        return $this->active;
    }

    /**
     * Set usercandidate
     *
     * @param string $usercandidate
     * @return SelectionProcessCandidate
     */
    public function setUserCandidate($usercandidate)
    {
        $this->usercandidate = $usercandidate;

        return $this;
    }

    /**
     * Get usercandidate
     *
     * @return string 
     */
    public function getUserCandidate()
    {
        return $this->usercandidate;
    }


    public function getUsername()
    {
        return $this->getUserCandidate();
    }

    /**
     * Set password
     *
     * @param string $password
     * @return SelectionProcessCandidate
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string 
     */
    public function getPassword()
    {
        return $this->password;
    }
    
    /**
     * Set selectionProcess
     *
     * @param Jaxxes\SeleccionProcesBundle\Entity\SelectionProcess $selectionProcess
     */
    public function setSelectionProcess(\Jaxxes\SeleccionProcesBundle\Entity\SelectionProcess $selectionProcess)
    {
        $this->selectionProcess = $selectionProcess;
    }
    
    /**
     * Get selectionProcess
     *
     * @return Jaxxes\SeleccionProcesBundle\Entity\SelectionProcess
     */
    public function getSelectionProcess()
    {
        return $this->selectionProcess;
    }
    
    /**
     * Set candidate
     *
     * @param Jaxxes\CandidateBundle\Entity\Candidate $candidate
     */
    public function setCandidate(\Jaxxes\CandidateBundle\Entity\Candidate $candidate)
    {
        $this->candidate = $candidate;
    }
    
    /**
     * Get candidate
     *
     * @return Jaxxes\CandidateBundle\Entity\Candidate
     */
    public function getCandidate()
    {
        return $this->candidate;
    }
    
	/**
	 * Add answers
	 * @param \Jaxxes\VirtualInterviewBundle\Entity\VirtualInterviewSelectionProcessCandidate $answers
	 * return SelectionProcessCandidate
	 * */
    
    public function addAnswer(\Jaxxes\VirtualInterviewBundle\Entity\VirtualInterviewSelectionProcessCandidate $answers  )
    {
		$this->answers[]=$answers;
		return $this;
	}
    
	public function getAnswers() 
    {
        return $this->answers;
    }
    
 	/**
	 * Add answersResumePrivate
	 * @param \Jaxxes\SeleccionProcesBundle\Entity\ResumePrivateCandidate $answersResumePrivate
	 * return SelectionProcessCandidate
	 * */   	 
    public function addAnswerResumePrivate(\Jaxxes\SeleccionProcesBundle\Entity\ResumePrivateCandidate $answersResumePrivate  )
    {
		$this->answersResumePrivate[]=$answersResumePrivate;
		return $this;
	}
    
	public function getAnswersResumePrivate() 
    {
        return $this->answersResumePrivate;
    }    
    
    
	function eraseCredentials()
	{
	}
	
    /**
     * Método requerido por la interfaz UserInterface
     */	
	function getRoles()
	{
		return array('ROLE_USUARIO');
	}

    /**
     * Set salt
     *
     * @param string $salt
     */
    public function setSalt($salt)
    {
        $this->salt = $salt;
    }	
		
    /**
     * Get salt
     *
     * @return string
     */
    public function getSalt()
    {
        return $this->salt;
    }

    /**
     * Set dateStart
     *
     * @param datetime $dateStart
     */
    public function setDateStart($dateStart)
    {
        $this->dateStart = $dateStart;
    }	
		
    /**
     * Get dateStart
     *
     * @return datetime
     */
    public function getDateStart()
    {
        return $this->dateStart;
    }
    
    /**
     * Set hourStart
     *
     * @param string $hourStart
     */
    public function setHourStart($hourStart)
    {
        $this->hourStart = $hourStart;
    }	
		
    /**
     * Get hourStart
     * 
     * @return string
     */
    public function getHourStart()
    {
        return $this->hourStart;
    }
    
    
    /**
     * Set finishtest
     *
     * @param boolean $finishtest
     * @return SelectionProcessCandidate
     */
    public function setFinishTest($finishtest)
    {
        $this->finishtest = $finishtest;

        return $this;
    }

    /**
     * Get finishtest
     *
     * @return boolean 
     */
    public function getFinishTest()
    {
        return $this->finishtest;
    }
}

src/Jaxxes/SeleccionProcesBundle/Controller/SelectionProcessCandidateController.php
<?php

namespace Jaxxes\SeleccionProcesBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use Jaxxes\SeleccionProcesBundle\Entity\SelectionProcess;
use Jaxxes\SeleccionProcesBundle\Entity\SelectionProcessCandidate;
use Jaxxes\SeleccionProcesBundle\Form\SelectionProcessCandidateType;
use Jaxxes\SeleccionProcesBundle\Form\SelectionProcessCandidateEditType;


class SelectionProcessCandidateController extends Controller
{
    
    public function newAction($idselectionprocess)
    {
        $em = $this->getDoctrine()->getManager();
        $entitySelectionProcess = $em->getRepository('SeleccionProcesBundle:SelectionProcess')->find($idselectionprocess);
        
        $entity = new SelectionProcessCandidate();
        $entity->setSelectionProcess($entitySelectionProcess);
        
        $form   = $this->createForm(new SelectionProcessCandidateType(), $entity);

        return $this->render('SeleccionProcesBundle:SelectionProcessCandidate:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView()
        ));
    }
    
    /**
     * Creates a new Register Rol Detail.
     *
     */
    public function createAction($idselectionprocess)
    {
        $entity  = new SelectionProcessCandidate();
        $request = $this->getRequest();
        $form    = $this->createForm(new SelectionProcessCandidateType(), $entity);

        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entitySelectionProcess = $em->getRepository('SeleccionProcesBundle:SelectionProcess')->find($idselectionprocess);
            $entity->setSelectionProcess($entitySelectionProcess);
            
            $entity->setSalt(md5(time()));

            $encoder = $this->get('security.encoder_factory')->getEncoder($entity);
            $passwordCodificado = $encoder->encodePassword(
                $entity->getPassword(),
                $entity->getSalt()
            );
            $entity->setPassword($passwordCodificado);

            
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('consultor_show', array('id' => $entity->getSelectionProcess()->getId() )));
        }
        print "formulario no valido";
		//throw $this->createNotFoundException(' ------- ' );
		return $this->redirect($this->generateUrl('backend_consultores'));

        /**
        return $this->render('SeleccionProcesBundle:SelectionProcessCandidate:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView()
        ));
        * */
    }
    
    /**
     * Finds and displays a Rol Detail entity
     *
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('SeleccionProcesBundle:SelectionProcessCandidate')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('No se ha encontrado la "candidato" asociado al proceso de seleccion');
        }

        $deleteForm = $this->createDeleteForm($id);

        return $this->render('SeleccionProcesBundle:SelectionProcessCandidate:show.html.twig', array(
            'entity'        => $entity,
            'delete_form'   => $deleteForm->createView(),
        ));
    }
    
    
    /**
     * Displays a form to edit an existing rol detail entity.
     *
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('SeleccionProcesBundle:SelectionProcessCandidate')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('No se ha encontrado el candidato solicitado');
        }

        $editForm = $this->createForm(new SelectionProcessCandidateEditType(), $entity);
        $deleteForm = $this->createDeleteForm($id);

        return $this->render('SeleccionProcesBundle:SelectionProcessCandidate:edit.html.twig', array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }
    
    /**
     * Edits an existing  rol detail entity.
     *
     */
    public function updateAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('SeleccionProcesBundle:SelectionProcessCandidate')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('No se ha encontrado el registro solicitado');
        }

        $editForm   = $this->createForm(new SelectionProcessCandidateEditType(), $entity);
        $deleteForm = $this->createDeleteForm($id);

        $request = $this->getRequest();

        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $entityTemp = $em->getRepository('SeleccionProcesBundle:SelectionProcessCandidate')->find($id);
            $entity->setPassword($entityTemp->getPassword());
            $entity->setSelectionProcess($entityTemp->getSelectionProcess());
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('consultor_show', array('id' => $entity->getSelectionProcess()->getId())));
        }

        return $this->render('SeleccionProcesBundle:SelectionProcessCandidate:edit.html.twig', array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }
    
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder(array('id' => $id))
            ->add('id', 'hidden')
            ->getForm()
        ;
    }
}

src/Jaxxes/SeleccionProcesBundle/Resources/views/SelectionProcessCandidate/edit.html.twig
{% extends '::consultor.html.twig' %}

{% block id 'selectionprocesscandidate' %}
{% block title %}Modificar Candidato{% endblock %}

{% block article %}

<div id="wrap">
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12 content">
                <h1>{{ block('title') }}</h1>
                <br>
                <br>
                <div class="row-fluid">
                    {{ form_start(edit_form, { 'action': path('sp_candidato_update' , { 'id': entity.id }) }) }}  
                        {{ form_errors(edit_form) }}
                        
                        <fieldset>
                            <div class="row-fluid">
                                <table class="record_properties">
                                    <tbody>
                                        <tr> 
                                            <td width="40px" ></td>
                                            <th width="180px">Proceso de Selección :</th>
                                            
                                            <td width="720px">{{ entity.selectionProcess  }}</td>
                                        </tr>
                                        <tr> 
                                            <td width="40px" ></td>
                                            <th  colspan=2 height="10px"></th>
                                        </tr>
                                        <tr> 
                                            <td width="40px" ></td>
                                            <th width="180px">Candidato :</th>
                                            <td width="720px">{{ form_widget(edit_form.candidate ) }}</td>
                                        </tr>
                                        <tr> 
                                            <td width="40px" ></td>
                                            <th  colspan=2 height="10px"></th>
                                        </tr>
                                        <tr> 
                                            <td width="40px" ></td>
                                            <th width="180px">Usuario :</th>
                                            <td width="720px">{{ form_widget(edit_form.userCandidate ) }}</td>
                                        </tr>
                                        <tr> 
                                            <td width="40px" ></td>
                                            <th colspan=2 height="10px"></th>
                                        </tr>
                                       
                                        <tr> 
                                            <td width="40px" ></td>
                                            <th colspan=2 height="10px"></th>
                                        </tr>

                                        <tr> 
                                            <td width="40px" ></td>
                                            <th width="180px">Activo :</th>
                                            <td width="720px">{{ form_widget(edit_form.active ) }}</td>
                                        </tr>
                                        <tr> 
                                            <td width="40px" ></td>
                                            <th colspan=2 height="10px"></th>
                                        </tr>
                                        
                                        <tr> 
                                            <td width="40px" ></td>
                                            <td colspan=2 >{{ form_widget(edit_form.guardar ) }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </fieldset>
                    {{ form_end(edit_form) }}
                </div>
                <ul class="record_actions">
                    <li>
                        <a href="{{ path('consultor_show', { 'id': entity.selectionProcess.id } ) }}">
                            Cancelar
                        </a>
                    </li>
                    <!--
                    <li>
                        <form action="{{ path('rol_delete', { 'id': entity.id }) }}" method="post">
                            {{ form_widget(delete_form) }}
                            <button type="submit">Borrar rol</button>
                        </form>
                    </li>
                    -->
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/Jaxxes/SeleccionProcesBundle/Resources/views/SelectionProcessCandidate/new.html.twig
{% extends '::consultor.html.twig' %}
{% block id 'selectionprocesscandidate' %}
{% block title %}Candidato{% endblock %}

{% block article %}

<div id="wrap">
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12 content">
                <br>
                <h1>{{ block('title') }}</h1>
                <br>
                <br>
                <div class="row-fluid">
                    
                    {{ form_start(form, { 'action': path('sp_candidato_create' , { 'idselectionprocess': entity.selectionProcess.id }) }) }}  
                        {{ form_errors(form) }}
                        
                        <fieldset>
                            <div class="row-fluid">
                                <table class="record_properties">
                                    <tbody>
                                        <tr> 
                                            <td width="40px" ></td>
                                            <th width="180px">Proceso de Selección :</th>
                                            <!--<td width="720px">{{ form_widget(form.selectionProcess ) }}</td>-->
                                            <td width="720px">{{ entity.selectionProcess  }}</td>
                                        </tr>
                                        <tr> 
                                            <td width="40px" ></td>
                                            <th  colspan=2 height="10px"></th>
                                        </tr>
                                        <tr> 
                                            <td width="40px" ></td>
                                            <th width="180px">Candidato :</th>
                                            <td width="720px">{{ form_widget(form.candidate ) }}</td>
                                        </tr>
                                        <tr> 
                                            <td width="40px" ></td>
                                            <th  colspan=2 height="10px"></th>
                                        </tr>
                                        <tr> 
                                            <td width="40px" ></td>
                                            <th width="180px">Usuario :</th>
                                            <td width="720px">{{ form_widget(form.userCandidate ) }}</td>
                                        </tr>
                                        <tr> 
                                            <td width="40px" ></td>
                                            <th colspan=2 height="10px"></th>
                                        </tr>
                                       
                                        <tr> 
                                            <td width="40px" ></td>
                                            <th width="180px">Password :</th>
                                            <td width="720px">{{ form_widget(form.password ) }}</td>
                                        </tr>
                                        <tr> 
                                            <td width="40px" ></td>
                                            <th colspan=2 height="10px"></th>
                                        </tr>
                                        <tr> 
                                            <td width="40px" ></td>
                                            <th width="180px">Activo :</th>
                                            <td width="720px">{{ form_widget(form.active ) }}</td>
                                        </tr>
                                        <tr> 
                                            <td width="40px" ></td>
                                            <th colspan=2 height="10px"></th>
                                        </tr>
                                        
                                        <tr> 
                                            <td width="40px" ></td>
                                            <td colspan=2 >{{ form_widget(form.guardar ) }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </fieldset>
                    {{ form_end(form) }}
                    
                </div>
                <br>
                <br>
                <!--
                <ul class="record_actions">
                    <li>
                        <a href="{{ path('rol_homepage') }}">
                            Volver al listado
                        </a>
                    </li>
                </ul>
                -->
            </div>
        </div>
    </div>
</div>
{% endblock %}